### ISSUE TITLE
Incorrect pageInfor object

### ISSUE THREAD

**Issue by Sp33ktrE** [zoontek/prisma-cursor-pagination#2]
### Bug summary

Hi, @zoontek, thanks for the package, i'm having a weird bug here, basically [pageInfo.hasPreviousPage] returns false despite there is a previous page since it's the second page/data and i can fetch previous data with startCursor.
note: i added where clause to prisma query args, i don't know if that's messing with the returned pageInfo object.

### Library version

0.2.2

### Steps to reproduce

-

### Reproducible sample code

```js
`const lastArgs = {
    ...findManyArgs,
    where: {
      ownerId: user?.id,
    },
  };

  const [totalCount, projects] = await Promise.all([
    prisma.project.count({
      where: {
        ownerId: user?.id,
      },
    }),
    prisma.project.findMany(lastArgs),
  ]);
  return { totalCount, ...toConnection(projects) };
```

**Comment by WangZhechao** [comment]
@Sp33ktrE 
This should not be a bug, but a compromise, where the returned `hasNextPage` is always `false` if the `last` and `before` parameters are passed, and conversely, `hasPreviousPage` is always `false` if the `first` and `after` parameters are passed because the library does not use additional query statements to get the real result.

```
 return {
          edges: copy.map((item) => ({ cursor: item.id, node: item })),
          pageInfo: {
            hasNextPage,
            endCursor: getLastItem(copy)?.id ?? null,
            hasPreviousPage: false,
            startCursor: copy[0]?.id ?? null,
          },
        };
···

return {
          edges: copy.map((item) => ({ cursor: item.id, node: item })),
          pageInfo: {
            hasNextPage: false,
            endCursor: getLastItem(copy)?.id ?? null,
            hasPreviousPage,
            startCursor: copy[0]?.id ?? null,
          },
        };
```

This is allowed in the relay paging specification: [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm)

If you want to get the real result, you should add an additional query statement to Promise.all and overwrite the query result with the return value of the toConnection() function

 Hope it can help you...

**Comment by zoontek** [comment]
@WangZhechao is right, this is not a bug as it's respect the spec. You use `first` / `before` for `inwards` pagination, `last` / `after` for `outwards` pagination.
